spring:
  datasource:
    platform: postgresql
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/data
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  mvc:
    view:
      prefix: /view/
      suffix: .html

seda:
  aggregation:
    threads: 4
    size: 1000

bars:
  download: /data/bars
cafe:
  download: /data/cafe
restaurants:
  download: /data/restaurants
coffeehouses:
  download: /data/coffeehouses

server:
  port: 8080